[project]
name = "study_movie"
version = "0.1.0"
description = "Review for study"
authors = [
    {name = "EstherCho-7", email = "dkgkqm777@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}



[tool.pdm]
distribution = false
